stages:
  - build
  - test

format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...

test:
  stage: test
  script:
    - go test ./...


build:
  stage: build
  script:
    - go build ./cmd/shop-api